port: 3000

replicaCount: 1

quizId: null # required

image:
  dockerRegistry:
    host: null # required

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

productsApiBaseUrl: null # required
